mysource <- function() {

     require(baseline)
     require(datasets)
     require(digest)
     require(graphics)
     require(grDevices)
     require(grid)
     require(lattice)
     require(latticeExtra)     
     require(memoise)
     require(methods)
     require(minpack.lm)
     require(FME)     
     require(NORMT3)
     require(signal)
     require(SparseM)
     require(stats)
     require(sm)
     require(wavelets)     
     require(utils)

     require(tcltk)
     require(tkrplot)
     require(gWidgets2)
     require(gWidgets2tcltk)
     options(guiToolkit="tcltk")

     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSAddFitComponent.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSClass.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSConstrain.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSElements.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSExtractGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFitCompClass.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFitAlgorithms.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSProcess.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSRead.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSRead.scienta.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSRead.vamas.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSRead.Genplot.r', encoding='UTF-8')

           

     source('Y:/LAVORI/R/RxpsG-2.1/R/RXPSGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSAnnotateGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSConstraintsGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSCoreLineList.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSCustomBaseline.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSCustomPlotGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSElemTabGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSEshiftGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSExportAsciiGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFNameList.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFilterGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFitLM.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSnlsLM.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFitInfoGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSFitParamInfoGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSModFitGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSGetHvalue.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSImportAsciiGUI.R', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSLatticeAnnotateGUI.R', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSMoveCompGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSMoveBaselineGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSOverlayGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSOverlayEngine.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSPreferencesGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSProcessCoreLineGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSQuantifyGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSReportGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSResetAnalysisGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSaveDataGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSampleInfoGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSaveRetrieveBkp.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSetCoreLineGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSetGraphDevGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSetFNameCLineGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSetWinSizeGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSetWDGUI.r', encoding='UTF-8')     
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSpectList.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSpectNameChangeGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSplitGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSurElmtIdentifyGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSurveyUtilities.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSSwitchBE.KE.GUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSTwoScalePlotGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSUtilities.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSVBTopGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSVmsCorrGUI.r', encoding='UTF-8')
     source('Y:/LAVORI/R/RxpsG-2.1/R/XPSZoomCurGUI.r', encoding='UTF-8')

     xps()
     setwd("Y:/LAVORI/R/Analysis/")

}
